### ISSUE TITLE
Cannot download from Baidu Drive

### ISSUE THREAD

**Issue by lcybuzz** [liutinglt/CE2P#11]
Thanks a lot for release the code and model! However, Baidu Drive is not available in my place. Would you please share them with Google Drive? @liutinglt

**Comment by liutinglt** [comment]
@lcybuzz Now, you can download from [Google Drive](https://drive.google.com/drive/folders/19I_MzMYzm2EYNvid9ySRvq66g_tZgkjm?usp=sharing)
