### ISSUE TITLE
error when sh build.sh

### ISSUE THREAD

**Issue by Zoesxw** [liutinglt/CE2P#26]
![image](https://user-images.githubusercontent.com/23716373/56586255-f147c300-6611-11e9-8102-587efe5f5687.png)
when I run sh build.sh, an error happened.

**Comment by jinx-USTC** [comment]
I met the same problem, have you solved it?

**Comment by BruceLoveDecimal** [comment]
I have met the same problem, how can u fix it? @Zoesxw
