### ISSUE TITLE
what's the right input size of pretrained model

### ISSUE THREAD

**Issue by Anikily** [liutinglt/CE2P#27]
I notice that the input size is 473 in paper, and the evaluate code set the size to 384

**Comment by nemonameless** [comment]
@Anikily @liutinglt 
I found that when I was training, the memory became more and more until the GPU was full, and there was no error message such as out of memory. 
I used torch. cuda. empty_cache() and del variables, which had no effect. 
Have you ever encountered this kind of situation?

**Comment by liutinglt** [comment]
@Anikily  This is the updated code, you can train with input size 473 as well, and the result will be higher.

**Comment by liutinglt** [comment]
@nemonameless please try smaller batch size

**Comment by Anikily** [comment]
@liutinglt so,what's the right size to reproduce the performance in Readme using pretrained model?

**Comment by liutinglt** [comment]
@Anikily 384
