### ISSUE TITLE
Is your pretrained model trained in train dataset or train and val dataset?

### ISSUE THREAD

**Issue by Nyquist0** [liutinglt/CE2P#35]
Hi, @liutinglt 
Is your pretrained model trained in _train dataset_ or _train and val dataset_?
Thanks.

**Comment by liutinglt** [comment]
@Nyquist0  The pretrained model is trained on Imagenet provided by MIT, and the provided LIP_epoch_149.pth is trained only on training set.

**Comment by Nyquist0** [comment]
Appreciate for your quick reply. : )
