### ISSUE TITLE
Poor result with the pretrained model LIP_epoch_149.pth downloaded from GoogleDrive.

### ISSUE THREAD

**Issue by maguro27** [liutinglt/CE2P#48]
I also encountered the issue as well as [https://github.com/liutinglt/CE2P/issues/34](url).
However, this issue does not provide a solution.
I do not change the part of weight loading and it does not output any error messages.
How do I fix it?

I investigated the output of the intermediate layers.
As a result, the output of "self.layer5" goes to -inf in the ResNet class.
Moreover, the network generates -inf though I exchange ABN to BN.
Thanks.

> My environment
GPU: Tesla V100
PyTorch: 1.6
ABN: https://github.com/mapillary/inplace_abn
Pre-trained model: LIP_epoch_149.pth downloaded from GoogleDrive

**Comment by CharlesPikachu** [comment]
we re-implement CE2P in this repo: https://github.com/SegmentationBLWX/sssegmentation, which has obtained better performance compared this repo. Maybe you can try this

**Comment by maguro27** [comment]
Thank you for your response.
It is great work!
I try to use your repository.
Thanks.
